remote_theme: vaibhavvikas/jekyll-theme-minimalistic
logo: /assets/img/logo.jpg
title: Afsaneh Narimani
favicon: true
color-scheme: light
platforms:
  - name: afsane.narimani@gmail.com
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:afsane.narimani@gmail.com
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/AfsanehNarimani
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/afsaneh-narimani-31211470/
